# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the dset modules
#

domain_set-y := domain_set_core.o

# dset core
obj-$(CONFIG_DOMAIN_SET) += domain_set.o

# hash types
obj-$(CONFIG_DOMAIN_SET_HASH_DOMAIN) += domain_set_hash_domain.o

